### ISSUE TITLE
start script when starting skype

### ISSUE THREAD

**Issue by JayPiEs** [andreashappe/indicator-applet-skype#5]
is it possible to automatically start the script when starting skype?

**Comment by andreashappe** [comment]
you can just create a shell script that starts skype as well as the integration thing.

**Comment by JayPiEs** [comment]
unfortunately i have no idea of programming :-(

how does it have to look?

something like this?

"#!/bin/bash
Skype
indicator-applet-skype.py
exit"

or could i put the execute command in some of these files?:

http://ubuntuone.com/p/aWf/
http://ubuntuone.com/p/aWg/

and what did this file say? could it be helpful? http://ubuntuone.com/p/aWi/

**Comment by JayPiEs** [comment]
or does the code have to look like this?:

Code:
#!/bin/bash

~/.Skype/indicator-applet-skype/indicator-applet-skype.py &

skype-wrapper &&

killall ~/.Skype/indicator-applet-skype/indicator-applet-skype.py

exit

**Comment by andreashappe** [comment]
almost

#!/bin/bash
Skype &
indicator-applet-skype.py &

**Comment by andreashappe** [comment]
oh, just saw the other one.. sorry.

yeah, the latter one looks better. It waits until skype is stopped again and then kills all running indicator-applet instances.

**Comment by JayPiEs** [comment]
hmm, with "Skype" command nothing happens, but "skype-wrapper" starts Skype but the script doesn't work...must the script be started with a delay?
how do i implement such delay?

**Comment by JayPiEs** [comment]
Code:
#!/bin/bash
skype-wrapper &&
import time
time.sleep(60) 
~/.Skype/indicator-applet-skype/indicator-applet-skype.py &&
killall ~/.Skype/indicator-applet-skype/indicator-applet-skype.py
exit

this still doesn't start the script, do you know if the path to the script has to be like that? my start script is in the folder of your indicator-script
